### ISSUE TITLE
Missing HMAC_SHA1

### ISSUE THREAD

**Issue by ljr1981** [EiffelWebFramework/cypress#1]
```
    Error code: VTCT
```

Error: type is based on unknown class.
What to do: use an identifier that is the name of a class in the universe.

Class: HMAC_SHA1_SIGNATURE_BUILDER
Unknown class name: HMAC_SHA1
Line: 20
      local
->      h: HMAC_SHA1
      do

**Comment by jocelyn** [comment]
I think this issue is not anymore relevant.
Closing.
